---
apiVersion: tekton.dev/v1beta1
kind: Task

metadata:
  name: cleanup
spec: 
  description: This task will clean up a workspace by deleting all the files.
  workspaces:
   steps:
    - name: remove
    
